PKG_VER=1.2.2
SRC_URL=https://github.com/libsndfile/libsndfile/archive/refs/tags/$PKG_VER.tar.gz
CMAKE_ARGS="-DBUILD_SHARED_LIBS=0 -DENABLE_EXTERNAL_LIBS=0 -DCMAKE_C_FLAGS=-fPIC -DENABLE_MPEG=0 -DBUILD_REGTEST=0 -DANDROID=1"
